# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: clj-kondo
        name: clj-kondo linter
        description: Run lint rules with clj-kondo
        types: [clojure]
        entry: scripts/hooks/pre-commit-clj-kondo
        language: script
        require_serial: true
        args: ["warning"]

      - id: cljfmt
        name: cljfmt formatter
        description: Run formatting rules with cljfmt
        types: [ clojure ]
        entry: scripts/hooks/pre-commit-cljfmt
        language: script
        require_serial: true
